spring.application.name=budgetting

# Chave de API do Gemini
spring.ai.google.genai.api-key=${GEMINI_API_KEY}

# Configurações do modelo de Chat
spring.ai.google.genai.chat.options.model=gemini-3.8-flash

# Log em nível DEBUG para Spring AI
logging.level.org.springframework.ai=DEBUG